; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

monitor_speed = 115200

lib_deps =
    FastLED
    ArduinoJson
    plerup/EspSoftwareSerial

; 关键：指向 mDNS 地址，注释则使用默认串口下载
; 注意：必须与 main.cpp 里的 OTA_HOSTNAME 一致（设备 mDNS 注册名 = OTA_HOSTNAME.local）
;upload_protocol = espota
;upload_port = smartcarrier_ESP32S3.local

